# Generated by Django 5.0.7 on 2024-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimodel',
            name='wfc_20min_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='お待たせ20分以上対応案件番号'),
        ),
        migrations.AlterField(
            model_name='kpimodel',
            name='wfc_30min_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='お待たせ30分以上対応案件番号'),
        ),
        migrations.AlterField(
            model_name='kpimodel',
            name='wfc_40min_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='お待たせ40分以上対応案件番号'),
        ),
        migrations.AlterField(
            model_name='kpimodel',
            name='wfc_60min_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='お待たせ60分以上対応案件番号'),
        ),
    ]
