# Generated by Django 5.0.7 on 2024-07-28 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_kpimodel_wfc_20min_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='kpimodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
