# Generated by Django 5.0.7 on 2024-07-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_kpimodel_created_at_alter_kpimodel_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KPIModel',
        ),
    ]
