# Generated by Django 5.0.7 on 2024-07-28 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calls', models.IntegerField(verbose_name='総着信数')),
                ('ivr_interruptions', models.IntegerField(verbose_name='自動音声ガイダンス途中切断数')),
                ('abandoned_during_operator', models.IntegerField(verbose_name='オペレーター呼出途中放棄数')),
                ('abandoned_in_ivr', models.IntegerField(verbose_name='留守電放棄件数')),
                ('abandoned_calls', models.IntegerField(verbose_name='放棄呼数')),
                ('voicemails', models.IntegerField(verbose_name='留守電数')),
                ('responses', models.IntegerField(verbose_name='応答件数')),
                ('response_rate', models.FloatField(verbose_name='応答率')),
                ('phone_inquiries', models.IntegerField(verbose_name='電話問い合わせ件数')),
                ('direct_handling', models.IntegerField(verbose_name='直受け対応件数')),
                ('direct_handling_rate', models.FloatField(verbose_name='直受け対応率')),
                ('callback_count_0_to_20_min', models.IntegerField(verbose_name='お待たせ0分～20分対応件数')),
                ('cumulative_callback_under_20_min', models.IntegerField(verbose_name='お待たせ20分以内累計対応件数')),
                ('cumulative_callback_rate_under_20_min', models.FloatField(verbose_name='お待たせ20分以内累計対応率')),
                ('callback_count_20_to_30_min', models.IntegerField(verbose_name='お待たせ20分～30分対応件数')),
                ('cumulative_callback_under_30_min', models.IntegerField(verbose_name='お待たせ30分以内累計対応件数')),
                ('cumulative_callback_rate_under_30_min', models.FloatField(verbose_name='お待たせ30分以内累計対応率')),
                ('callback_count_30_to_40_min', models.IntegerField(verbose_name='お待たせ30分～40分対応件数')),
                ('cumulative_callback_under_40_min', models.IntegerField(verbose_name='お待たせ40分以内累計対応件数')),
                ('cumulative_callback_rate_under_40_min', models.FloatField(verbose_name='お待たせ40分以内累計対応率')),
                ('callback_count_40_to_60_min', models.IntegerField(verbose_name='お待たせ40分～60分対応件数')),
                ('cumulative_callback_under_60_min', models.IntegerField(verbose_name='お待たせ60分以内累計対応件数')),
                ('cumulative_callback_rate_under_60_min', models.FloatField(verbose_name='お待たせ60分以内累計対応率')),
                ('callback_count_over_60_min', models.IntegerField(verbose_name='お待たせ60分以上対応件数')),
                ('waiting_for_callback_over_20min', models.IntegerField(verbose_name='お待たせ20分以上対応件数')),
                ('waiting_for_callback_over_30min', models.IntegerField(verbose_name='お待たせ30分以上対応件数')),
                ('waiting_for_callback_over_40min', models.IntegerField(verbose_name='お待たせ40分以上対応件数')),
                ('waiting_for_callback_over_60min', models.IntegerField(verbose_name='お待たせ60分以上対応件数')),
                ('wfc_20min_list', models.CharField(blank=True, max_length=255, null=True, verbose_name='お待たせ20分以上対応案件番号')),
                ('wfc_30min_list', models.CharField(blank=True, max_length=255, null=True, verbose_name='お待たせ30分以上対応案件番号')),
                ('wfc_40min_list', models.CharField(blank=True, max_length=255, null=True, verbose_name='お待たせ40分以上対応案件番号')),
                ('wfc_60min_list', models.CharField(blank=True, max_length=255, null=True, verbose_name='お待たせ60分以上対応案件番号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
