# Generated by Django 5.0.7 on 2024-08-03 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='オペレーター名')),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='CTStage名')),
                ('sweet_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sweet名')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='スーパーバイザーかどうか')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブかどうか')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
